姓名: 姓名
在……之上:
workflow_dispatch:
输入:
package_name:
描述: "游戏包名："
必需的: 正确

工作:
建立:
连续的: ubuntu-最新
步骤:
    - uses: 操作/结帐@v4
    - uses: 操作/设置-Java@v4
和……一起:
分布: temurin
java版: 11
缓存: G拉德尔
-跑: |
chmod+x./gradlew
SED-i的/moduleDescription="/moduleDescription="(${{github.event.inputs.package_name}})/g'module.gradle
SED-i"s/com。游戏。PackageName/${{github。事件。输入.包名称}/g"模块/src/main/cpp/Game.h
./gradlew：模块：assemblyRelease
    - uses: 4操作/上载工件@v
和……一起:
姓名: zygisk-il2cppdumper
        path: out/magisk_module_release/
